### PR TITLE
add wallet, sub-account sapi endpoints

### PR DESCRIPTION
**Pull request by ishuen**
* Wallet
1. GET /sapi/v1/system/status to query system status
2. GET /sapi/v1/account/status to query account status
3. GET /sapi/v1/account/apiTradingStatus to query account API trading status
4. GET /sapi/v1/asset/dribblet to query dust log
5. GET /sapi/v1/asset/assetDetail to query asset detail
6. GET /sapi/v1/asset/tradeFee to query trade fee

* Sub-Account
1. GET /sapi/v3/sub-account/assets to query sub-account assets

### CODE REVIEW

**Comment by 2pd** [comment]
@ishuen  please those endpoints in the comment.

**Comment by ishuen** [comment]
> @ishuen please those endpoints in the comment.

Sure, I edited the commit comment. Please check if it's informative enough.

**Comment by 2pd** [comment]
please remove value of `email_address`  for `email` in /sapi/v3/sub-account/assets

**Comment by ishuen** [comment]
> please remove value of `email_address` for `email` in `/sapi/v3/sub-account/assets`.

Okay, the placeholder is removed.

**Pull request merged**
